src/controllers/hosts.rs
src/models/host.rs

implement From for conversion

---

src/controllers/hosts.rs
src/main.rs
src/services/host.rs
src/services/mod.rs

add services

---

Cargo.toml
build.rs
proto/node.proto
src/controllers/hosts.rs
src/models/host.rs
src/services/host.rs
src/services/mod.rs
src/services/rpc/client.rs
src/services/rpc/mod.rs

gRPC intro

---

proto/node.proto

Too much trouble at this point, revisit later.

remove uuid from protoc

---

src/controllers/hosts.rs
src/lib.rs
src/services/mod.rs

`Backend` will be a struct to hold services, for now it will hold only `HostService`, but soon `VmService` will join.
Not sure if it's an optimal solution, but I can't think of anything better right now.

add Backend object to hold services

---

migrations/2020-06-22-163236_create_vms/down.sql
migrations/2020-06-22-163236_create_vms/up.sql
src/controllers/hosts.rs
src/controllers/mod.rs
src/controllers/vms.rs
src/lib.rs
src/models/mod.rs
src/models/vm.rs
src/schema.rs
src/services/mod.rs
src/services/vm.rs

Currently only DB operations:
- add
- get all
- get by id

Introduce the /vms endpoint

---

src/controllers/hosts.rs
src/services/host.rs
src/services/mod.rs
src/services/rpc/client.rs

Improve installation:
After installation completes, qarax will establish a connection to qarax-node and will check qarax-node's health

add health check to installation

---

src/controllers/hosts.rs
src/services/host.rs
src/services/util/ansible.rs

Minor fixes

---

src/controllers/vms.rs
src/models/host.rs
src/services/host.rs
src/services/rpc/client.rs
src/services/vm.rs

Preliminary work:
- Implement endpoint /vms/<id>/start
- Send VM configuration from database
TODO:
- Implement status changing
- Start VM on separate thread
- Error handling

implement initial VM start

---

playbooks/roles/setup_host/tasks/build_qarax_node.yml
playbooks/roles/setup_host/tasks/files/start_qarax_node.sh

TODO: make qarax-node a service

minor improvements to the ansible tasks

---

src/services/host.rs
src/services/rpc/client.rs

An error will be thrown if there is no connection within 10 seconds
TODO:
- Fail installation and set host status accordingly (near future)
- Make timeout configurable (far future)

implement a deadline for connecting to qarax-node

---

src/services/host.rs
src/services/rpc/client.rs

General improvements to the negative flow of host installation. More work to be done.

Installation errors

---

scripts/create_db.sh

Use postgres user to run the psql commands

Fix scripts/create_db.sh

---

proto/node.proto
qarax-node/src/network/dhcp.rs
qarax-node/src/network/mod.rs
qarax-node/src/vm_service.rs
qarax-node/src/vmm_handler.rs
src/controllers/vms.rs
src/models/vm.rs
src/services/rpc/client.rs
src/services/vm.rs

qarax-node will now report back the `VmConfig` object containing the
address it had obtained from the DHCP server.
qarax will then save this address in the database.

save IP address assigned to VM in the database

---

src/controllers/hosts.rs
src/models/host.rs
src/models/mod.rs
src/services/host.rs

TODO: rename to just Host::add

add error handling for Host::add_host flow

---

src/controllers/hosts.rs
src/models/host.rs

Change the `NewHost` `user` field to `host_user` and remove the path to qarax-node
(node path needed only for installation, not needed for adding host)

Update NewHost struct to match Host struct

---

README.md

Commit 042b4f5ee changed the field from `user` to `host_user`

user -> host_user

---

README.md
qarax.yaml
src/controllers/drives.rs
src/controllers/hosts.rs
src/controllers/kernels.rs
src/controllers/storage.rs
src/controllers/vms.rs

Update the configuration file for the SDK (swagger) with definitions of the responses.
Update the qarax API (controllers files) to response to POST requests with an id key without a prefix (id instead host_id)..

Update API responses

---

src/services/vm.rs

set host_id after running a VM

---

qarax.yaml

Use operationId to generate better method namesx

Change API yaml definition to OpenAPI

---

e2e/run_tests.sh

e2e: create script to run e2e tests

---

e2e/.gitignore
e2e/conftest.py
e2e/e2e.py
e2e/requirements.txt
e2e/run_tests.sh
e2e/terraform.py
e2e/terraform/cloud_init.cfg

create snapshot for e2e VM
